name: zip and upload
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release-${{github.ref_name}}.zip'
          exclusions: '*.git* *.github*'
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
            name: upload-output
            path: release-${{github.ref_name}}.zip